# NumPy - Thinking in Arrays

In [1]:
import numpy as np

In [2]:
np.array([])

array([], dtype=float64)

In [3]:
np.array([6, 56, 6565, 5323])

array([   6,   56, 6565, 5323])

In [5]:
np.array ([5, 6., 34, 123])

array([   5.,    6.,   34.,  123.])

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [8]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [10]:
np.arange(0, np.pi , np.pi / 20)

array([ 0.        ,  0.15707963,  0.31415927,  0.4712389 ,  0.62831853,
        0.78539816,  0.9424778 ,  1.09955743,  1.25663706,  1.41371669,
        1.57079633,  1.72787596,  1.88495559,  2.04203522,  2.19911486,
        2.35619449,  2.51327412,  2.67035376,  2.82743339,  2.98451302])

In [11]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [12]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [15]:
np.logspace(1,100,3)

array([  1.00000000e+001,   3.16227766e+050,   1.00000000e+100])

In [16]:
a = np.arange(5)

In [17]:
a.ndim

1

In [18]:
a = np.arange(25)

In [19]:
a.ndim

1

In [20]:
a.shape

(25,)

In [21]:
a.size

25

In [22]:
a.dtype

dtype('int64')

In [23]:
a.itemsize

8

In [24]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
a.shape = (5,5)

In [26]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
b = np.arange(25)
b.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
c = np.array([6, 29., 296, 8128])
c.dtype

dtype('float64')

In [34]:
np.array(np.zeros(64), ndmin=2)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [36]:
np.array([6, 8, 256,290348], dtype=np.int8)

array([ 6,  8,  0, 44], dtype=int8)

In [39]:
np.array(['I will have a length of 6', 'so will I!'], dtype='S6')

array([b'I will', b'so wil'], 
      dtype='|S6')

# Slicing and views

In [41]:
a = np.arange(8)

In [42]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
a[2:-1]

array([2, 3, 4, 5, 6])

In [46]:
a[1::3]

array([1, 4, 7])

In [54]:
a1 = np.arange(25).reshape(5, 5)

# temp = np.arange(25)
# a1 = temp.reshape(5,5)
# del(temp)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
l1 = a1.tolist()
l1

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [56]:
l2 = []
for inner in l1[::2]:
    l2.append(inner[1::2])
l2

[[1, 3], [11, 13], [21, 23]]

In [64]:
l3 = [inner[1::2] for inner in l1[::2]]
l3

[[1, 3], [11, 13], [21, 23]]

In [60]:
a3 = a1[::2, 1::2]
a3

array([[ 1,  3],
       [11, 13],
       [21, 23]])

In [65]:
a= np.arange(6)
b= a[1::2]
b[1]=42
a

array([ 0,  1,  2, 42,  4,  5])

In [67]:
b

array([ 1, 42,  5])

In [68]:
b.base

array([ 0,  1,  2, 42,  4,  5])

In [69]:
b.data

In [72]:
a.view('i4')

array([ 0,  0,  1,  0,  2,  0, 42,  0,  4,  0,  5,  0], dtype=int32)

## Arithmatic and Broadcasting

In [73]:
a -1

array([-1,  0,  1, 41,  3,  4])

In [74]:
a+a

array([ 0,  2,  4, 84,  8, 10])

In [75]:
2*a**2 + 3*a + 1

array([   1,    6,   15, 3655,   45,   66])

In [76]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [77]:
b = np.array([
    [42], [43]
])

In [78]:
b

array([[42],
       [43]])

In [79]:
a * b

array([[  0,  42],
       [ 86, 129]])

## Fancy Indexing

In [80]:
a = 2 * np.arange(8)**2 + 1
a

array([ 1,  3,  9, 19, 33, 51, 73, 99])

In [81]:
a[[3,-1,1]]

array([19, 99,  3])

In [82]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
a >= 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [84]:
m = a >= 5

In [85]:
m

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [86]:
a[m]

array([5, 6, 7, 8])

In [87]:
a[a>=5]

array([5, 6, 7, 8])

In [88]:
b

array([[42],
       [43]])

In [89]:
b=np.arange(5, 5+9).reshape(3,3)

In [90]:
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [91]:
np.max(a)

8

In [92]:
np.sum(a)

36

In [94]:
np.sum(a,axis=0)

array([ 9, 12, 15])

In [95]:
np.sum(a,axis=1)

array([ 3, 12, 21])